### ISSUE TITLE
Create GUI to interact with Dockerfreeze

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/dockerfreeze#37]
Create GUI to interact with Dockerfreeze

**Comment by JesterOrNot** [comment]
@Kreyren would you be interested in working on this?

**Comment by JesterOrNot** [comment]
Note: It can be written in anything :)

**Comment by Kreyren** [comment]
I would be interested in contributing and in proposing a mock-up, but i don't feel confident in the GUI development in rust aldo implementing that in piston might be fun, but i guess that it would make more sense in python.

ping @uniminin do you want to be useful?

**Comment by loannaflip** [comment]
> I would be interested in contributing and in proposing a mock-up, but i don't feel confident in the GUI development in rust aldo implementing that in piston might be fun, but i guess that it would make more sense in python.
> 
> ping @Uniminin do you want to be useful?

Yes

**Comment by Kreyren** [comment]
@JesterOrNot Can you brainstorm him on what would you want for GUI in python?

**Comment by JesterOrNot** [comment]
A bunch of toggles i.e.
Add Environment variables
Pretty print Dockerfile ---- For readability with a slight time increase
Install user packages
Gitpod ready
Vagrant

**Comment by JesterOrNot** [comment]
And a build button

**Comment by JesterOrNot** [comment]
If you guys make the GUI I'll do the TUI

**Comment by Kreyren** [comment]
@JesterOrNot He's in different timezone, but i've gave him the info for what needs to be done.

**Comment by JesterOrNot** [comment]
Ok!

**Comment by Kreyren** [comment]
@JesterOrNot He made this

```python
# BASIC PYTHON GUI WITH BUTTONS. THANKS TO Tkinter!
# Copyright Uniminin 2020
from tkinter import *

# Window
window_title = "Docker Freeze Gui"
window = Tk()
window.title(window_title)
window.geometry('716x400')

button1 = Button(window, text="Add Environment variablese")
button1.grid(column=1,
             row=0,
             padx=2,
             pady=2)

button2 = Button(window, text="Pretty print Dockerfile")
button2.grid(column=2,
             row=0,
             padx=2,
             pady=2)

button3 = Button(window, text="Install user packages")
button3.grid(column=3,
             row=0,
             padx=2,
             pady=2)

button4 = Button(window, text="Vagrant")
button4.grid(column=4,
             row=0,
             padx=2,
             pady=2, )

button5 = Button(window, text="Gitpod ready")
button5.grid(column=5,
             row=0,
             padx=2,
             pady=2)

if name == "main":
    window.mainloop()
``` 

Do you want to use it?

**Comment by JesterOrNot** [comment]
Can I see the repo?

**Comment by loannaflip** [comment]
> Can I see the repo?

i need to know what you're expecting in the gui. please specify everything again clearly, then i'll make it

**Comment by Kreyren** [comment]
@Uniminin See https://github.com/gitpod-io/dockerfreeze/issues/37#issuecomment-594070900

So this is expected to be a GUI in python with a toggle buttons i.e:
![image](https://user-images.githubusercontent.com/11302521/75905791-cb03ce00-5e45-11ea-8391-249b9a5a426e.png)

with following text next to them
- Add Environment variables
- Pretty print Dockerfile ---- For readability with a slight time increase
- Install user packages
- Gitpod ready
- Vagrant

ideally do not use gtk because it's inefficient on system resources and i will like you more if you cythonize it and provide tests ^-^

**Comment by JesterOrNot** [comment]
Yes that looks great, Ideally we should add a build button

**Comment by JesterOrNot** [comment]
Then we can use system calls to connect the rust and python code

**Comment by JesterOrNot** [comment]
Done!
